# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./RecentTest
      run: swift build -v
    - name: Danger
      working-directory: ./RecentTest
      run: danger-swift ci
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: DangerSecondTest
      uses: danger/swift@3.16.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
